# Generated by Django 5.2.4 on 2025-10-30 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "study_time_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="assignment__user_id_9c8648_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="assignment__timesta_b88926_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "submission_id"),
                        name="unique_submission_per_user",
                    )
                ],
            },
        ),
    ]
